
version: '2.1'

services:
  PODServices:
    network_mode: bridge

    image: ecare
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ecare
    ports:
      - 8081:8081
    expose:
            - 8081
    depends_on:
      - db
    links:
      - db
environment:

spring.datasource.url=jdbc:mysql://localhost/userdetails?useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernet.dialect=org.hibernet.dialect.MySQL5Dialect




 
services:
  db:
   network_mode: bridge
    image: mysql:5.5.62
    container_name: db
    


    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: mysqlimage/mysqlimage
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata:
